import "prismjs/plugins/line-numbers/prism-line-numbers.css"
import "./globals.css"
import "./prism-atom-dark.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
