import './globals.css'
import './prism-atom-dark.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
  metadataBase: new URL('https://paulkhoza.co.za'),
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
